services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin123
